### ISSUE TITLE
JS Error on Checkout addressOptions is not defined

### ISSUE THREAD

**Issue by ecompleteClem** [PayFast/mod-magento_2.3.0#2]
Hi,

We are using your extension with Amasty One Step Checkout and after installing the module we receive a JS Error on Checkout.

addressOptions is not defined.

This occurs as soon as you go to checkout. 

Could you please take a look and let us know once this has been fixed.

**Comment by PF-Thinus** [comment]
Hi @ecompleteClem, 

I would like for you to run "grep -rinH 'addressOption' ./app/code/Payfast/Payfast" inside the root directory of your project to check for any code referencing the 'addressOption' variable. If you find any results please open a support ticket so that we can assist further.

Could you please install the PayFast module on a separate project, test the transaction and then install Amasty One Step Checkout on top of that project?

Please follow up on support@payfast.co.za for further assistance.
